// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module streaming_attention_streaming_attention_Pipeline_BETA (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        score_reload,
        score_1_reload,
        score_2_reload,
        score_3_reload,
        score_4_reload,
        score_5_reload,
        score_6_reload,
        score_7_reload,
        score_8_reload,
        score_9_reload,
        score_10_reload,
        score_11_reload,
        score_12_reload,
        score_13_reload,
        score_14_reload,
        score_15_reload,
        tile_max_reload,
        beta_15_out,
        beta_15_out_ap_vld,
        beta_14_out,
        beta_14_out_ap_vld,
        beta_13_out,
        beta_13_out_ap_vld,
        beta_12_out,
        beta_12_out_ap_vld,
        beta_11_out,
        beta_11_out_ap_vld,
        beta_10_out,
        beta_10_out_ap_vld,
        beta_9_out,
        beta_9_out_ap_vld,
        beta_8_out,
        beta_8_out_ap_vld,
        beta_7_out,
        beta_7_out_ap_vld,
        beta_6_out,
        beta_6_out_ap_vld,
        beta_5_out,
        beta_5_out_ap_vld,
        beta_4_out,
        beta_4_out_ap_vld,
        beta_3_out,
        beta_3_out_ap_vld,
        beta_2_out,
        beta_2_out_ap_vld,
        beta_1_out,
        beta_1_out_ap_vld,
        beta_out,
        beta_out_ap_vld,
        grp_fu_1556_p_din0,
        grp_fu_1556_p_din1,
        grp_fu_1556_p_opcode,
        grp_fu_1556_p_dout0,
        grp_fu_1556_p_ce,
        grp_fu_1584_p_din0,
        grp_fu_1584_p_din1,
        grp_fu_1584_p_dout0,
        grp_fu_1584_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] score_reload;
input  [31:0] score_1_reload;
input  [31:0] score_2_reload;
input  [31:0] score_3_reload;
input  [31:0] score_4_reload;
input  [31:0] score_5_reload;
input  [31:0] score_6_reload;
input  [31:0] score_7_reload;
input  [31:0] score_8_reload;
input  [31:0] score_9_reload;
input  [31:0] score_10_reload;
input  [31:0] score_11_reload;
input  [31:0] score_12_reload;
input  [31:0] score_13_reload;
input  [31:0] score_14_reload;
input  [31:0] score_15_reload;
input  [31:0] tile_max_reload;
output  [31:0] beta_15_out;
output   beta_15_out_ap_vld;
output  [31:0] beta_14_out;
output   beta_14_out_ap_vld;
output  [31:0] beta_13_out;
output   beta_13_out_ap_vld;
output  [31:0] beta_12_out;
output   beta_12_out_ap_vld;
output  [31:0] beta_11_out;
output   beta_11_out_ap_vld;
output  [31:0] beta_10_out;
output   beta_10_out_ap_vld;
output  [31:0] beta_9_out;
output   beta_9_out_ap_vld;
output  [31:0] beta_8_out;
output   beta_8_out_ap_vld;
output  [31:0] beta_7_out;
output   beta_7_out_ap_vld;
output  [31:0] beta_6_out;
output   beta_6_out_ap_vld;
output  [31:0] beta_5_out;
output   beta_5_out_ap_vld;
output  [31:0] beta_4_out;
output   beta_4_out_ap_vld;
output  [31:0] beta_3_out;
output   beta_3_out_ap_vld;
output  [31:0] beta_2_out;
output   beta_2_out_ap_vld;
output  [31:0] beta_1_out;
output   beta_1_out_ap_vld;
output  [31:0] beta_out;
output   beta_out_ap_vld;
output  [31:0] grp_fu_1556_p_din0;
output  [31:0] grp_fu_1556_p_din1;
output  [0:0] grp_fu_1556_p_opcode;
input  [31:0] grp_fu_1556_p_dout0;
output   grp_fu_1556_p_ce;
output  [31:0] grp_fu_1584_p_din0;
output  [31:0] grp_fu_1584_p_din1;
input  [31:0] grp_fu_1584_p_dout0;
output   grp_fu_1584_p_ce;

reg ap_idle;
reg beta_15_out_ap_vld;
reg beta_14_out_ap_vld;
reg beta_13_out_ap_vld;
reg beta_12_out_ap_vld;
reg beta_11_out_ap_vld;
reg beta_10_out_ap_vld;
reg beta_9_out_ap_vld;
reg beta_8_out_ap_vld;
reg beta_7_out_ap_vld;
reg beta_6_out_ap_vld;
reg beta_5_out_ap_vld;
reg beta_4_out_ap_vld;
reg beta_3_out_ap_vld;
reg beta_2_out_ap_vld;
reg beta_1_out_ap_vld;
reg beta_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln100_fu_425_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln100_reg_736;
reg   [0:0] icmp_ln100_reg_736_pp0_iter1_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter2_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter3_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter4_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter5_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter6_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter7_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter8_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter9_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter10_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter11_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter12_reg;
reg   [0:0] icmp_ln100_reg_736_pp0_iter13_reg;
wire   [31:0] tmp_4_fu_437_p18;
reg   [31:0] tmp_4_reg_740;
wire   [3:0] trunc_ln102_fu_475_p1;
reg   [3:0] trunc_ln102_reg_745;
reg   [3:0] trunc_ln102_reg_745_pp0_iter1_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter2_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter3_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter4_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter5_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter6_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter7_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter8_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter9_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter10_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter11_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter12_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter13_reg;
reg   [3:0] trunc_ln102_reg_745_pp0_iter14_reg;
reg   [31:0] x_assign_1_reg_749;
reg   [4:0] j_fu_126;
wire   [4:0] add_ln100_fu_431_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_2;
wire    ap_block_pp0_stage0;
reg   [31:0] beta_fu_130;
reg   [31:0] beta_1_fu_134;
reg   [31:0] beta_2_fu_138;
reg   [31:0] beta_3_fu_142;
reg   [31:0] beta_4_fu_146;
reg   [31:0] beta_5_fu_150;
reg   [31:0] beta_6_fu_154;
reg   [31:0] beta_7_fu_158;
reg   [31:0] beta_8_fu_162;
reg   [31:0] beta_9_fu_166;
reg   [31:0] beta_10_fu_170;
reg   [31:0] beta_11_fu_174;
reg   [31:0] beta_12_fu_178;
reg   [31:0] beta_13_fu_182;
reg   [31:0] beta_14_fu_186;
reg   [31:0] beta_15_fu_190;
wire    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_done_reg = 1'b0;
end

streaming_attention_mux_165_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_165_32_1_1_x_U325(
    .din0(score_reload),
    .din1(score_1_reload),
    .din2(score_2_reload),
    .din3(score_3_reload),
    .din4(score_4_reload),
    .din5(score_5_reload),
    .din6(score_6_reload),
    .din7(score_7_reload),
    .din8(score_8_reload),
    .din9(score_9_reload),
    .din10(score_10_reload),
    .din11(score_11_reload),
    .din12(score_12_reload),
    .din13(score_13_reload),
    .din14(score_14_reload),
    .din15(score_15_reload),
    .din16(ap_sig_allocacmp_j_2),
    .dout(tmp_4_fu_437_p18)
);

streaming_attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln100_fu_425_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_126 <= add_ln100_fu_431_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_126 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln100_reg_736_pp0_iter10_reg <= icmp_ln100_reg_736_pp0_iter9_reg;
        icmp_ln100_reg_736_pp0_iter11_reg <= icmp_ln100_reg_736_pp0_iter10_reg;
        icmp_ln100_reg_736_pp0_iter12_reg <= icmp_ln100_reg_736_pp0_iter11_reg;
        icmp_ln100_reg_736_pp0_iter13_reg <= icmp_ln100_reg_736_pp0_iter12_reg;
        icmp_ln100_reg_736_pp0_iter2_reg <= icmp_ln100_reg_736_pp0_iter1_reg;
        icmp_ln100_reg_736_pp0_iter3_reg <= icmp_ln100_reg_736_pp0_iter2_reg;
        icmp_ln100_reg_736_pp0_iter4_reg <= icmp_ln100_reg_736_pp0_iter3_reg;
        icmp_ln100_reg_736_pp0_iter5_reg <= icmp_ln100_reg_736_pp0_iter4_reg;
        icmp_ln100_reg_736_pp0_iter6_reg <= icmp_ln100_reg_736_pp0_iter5_reg;
        icmp_ln100_reg_736_pp0_iter7_reg <= icmp_ln100_reg_736_pp0_iter6_reg;
        icmp_ln100_reg_736_pp0_iter8_reg <= icmp_ln100_reg_736_pp0_iter7_reg;
        icmp_ln100_reg_736_pp0_iter9_reg <= icmp_ln100_reg_736_pp0_iter8_reg;
        trunc_ln102_reg_745_pp0_iter10_reg <= trunc_ln102_reg_745_pp0_iter9_reg;
        trunc_ln102_reg_745_pp0_iter11_reg <= trunc_ln102_reg_745_pp0_iter10_reg;
        trunc_ln102_reg_745_pp0_iter12_reg <= trunc_ln102_reg_745_pp0_iter11_reg;
        trunc_ln102_reg_745_pp0_iter13_reg <= trunc_ln102_reg_745_pp0_iter12_reg;
        trunc_ln102_reg_745_pp0_iter14_reg <= trunc_ln102_reg_745_pp0_iter13_reg;
        trunc_ln102_reg_745_pp0_iter2_reg <= trunc_ln102_reg_745_pp0_iter1_reg;
        trunc_ln102_reg_745_pp0_iter3_reg <= trunc_ln102_reg_745_pp0_iter2_reg;
        trunc_ln102_reg_745_pp0_iter4_reg <= trunc_ln102_reg_745_pp0_iter3_reg;
        trunc_ln102_reg_745_pp0_iter5_reg <= trunc_ln102_reg_745_pp0_iter4_reg;
        trunc_ln102_reg_745_pp0_iter6_reg <= trunc_ln102_reg_745_pp0_iter5_reg;
        trunc_ln102_reg_745_pp0_iter7_reg <= trunc_ln102_reg_745_pp0_iter6_reg;
        trunc_ln102_reg_745_pp0_iter8_reg <= trunc_ln102_reg_745_pp0_iter7_reg;
        trunc_ln102_reg_745_pp0_iter9_reg <= trunc_ln102_reg_745_pp0_iter8_reg;
        x_assign_1_reg_749 <= grp_fu_1556_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln100_reg_736 <= icmp_ln100_fu_425_p2;
        icmp_ln100_reg_736_pp0_iter1_reg <= icmp_ln100_reg_736;
        trunc_ln102_reg_745_pp0_iter1_reg <= trunc_ln102_reg_745;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd10))) begin
        beta_10_fu_170 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd11))) begin
        beta_11_fu_174 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd12))) begin
        beta_12_fu_178 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd13))) begin
        beta_13_fu_182 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd14))) begin
        beta_14_fu_186 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd15))) begin
        beta_15_fu_190 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd1))) begin
        beta_1_fu_134 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd2))) begin
        beta_2_fu_138 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd3))) begin
        beta_3_fu_142 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd4))) begin
        beta_4_fu_146 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd5))) begin
        beta_5_fu_150 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd6))) begin
        beta_6_fu_154 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd7))) begin
        beta_7_fu_158 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd8))) begin
        beta_8_fu_162 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd9))) begin
        beta_9_fu_166 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln102_reg_745_pp0_iter14_reg == 4'd0))) begin
        beta_fu_130 <= grp_fu_1584_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln100_fu_425_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_4_reg_740 <= tmp_4_fu_437_p18;
        trunc_ln102_reg_745 <= trunc_ln102_fu_475_p1;
    end
end

always @ (*) begin
    if (((icmp_ln100_fu_425_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_10_out_ap_vld = 1'b1;
    end else begin
        beta_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_11_out_ap_vld = 1'b1;
    end else begin
        beta_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_12_out_ap_vld = 1'b1;
    end else begin
        beta_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_13_out_ap_vld = 1'b1;
    end else begin
        beta_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_14_out_ap_vld = 1'b1;
    end else begin
        beta_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_15_out_ap_vld = 1'b1;
    end else begin
        beta_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_1_out_ap_vld = 1'b1;
    end else begin
        beta_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_2_out_ap_vld = 1'b1;
    end else begin
        beta_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_3_out_ap_vld = 1'b1;
    end else begin
        beta_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_4_out_ap_vld = 1'b1;
    end else begin
        beta_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_5_out_ap_vld = 1'b1;
    end else begin
        beta_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_6_out_ap_vld = 1'b1;
    end else begin
        beta_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_7_out_ap_vld = 1'b1;
    end else begin
        beta_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_8_out_ap_vld = 1'b1;
    end else begin
        beta_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_9_out_ap_vld = 1'b1;
    end else begin
        beta_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln100_reg_736_pp0_iter13_reg == 1'd1))) begin
        beta_out_ap_vld = 1'b1;
    end else begin
        beta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_431_p2 = (ap_sig_allocacmp_j_2 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign beta_10_out = beta_10_fu_170;

assign beta_11_out = beta_11_fu_174;

assign beta_12_out = beta_12_fu_178;

assign beta_13_out = beta_13_fu_182;

assign beta_14_out = beta_14_fu_186;

assign beta_15_out = beta_15_fu_190;

assign beta_1_out = beta_1_fu_134;

assign beta_2_out = beta_2_fu_138;

assign beta_3_out = beta_3_fu_142;

assign beta_4_out = beta_4_fu_146;

assign beta_5_out = beta_5_fu_150;

assign beta_6_out = beta_6_fu_154;

assign beta_7_out = beta_7_fu_158;

assign beta_8_out = beta_8_fu_162;

assign beta_9_out = beta_9_fu_166;

assign beta_out = beta_fu_130;

assign grp_fu_1556_p_ce = 1'b1;

assign grp_fu_1556_p_din0 = tmp_4_reg_740;

assign grp_fu_1556_p_din1 = tile_max_reload;

assign grp_fu_1556_p_opcode = 2'd1;

assign grp_fu_1584_p_ce = 1'b1;

assign grp_fu_1584_p_din0 = 32'd0;

assign grp_fu_1584_p_din1 = x_assign_1_reg_749;

assign icmp_ln100_fu_425_p2 = ((ap_sig_allocacmp_j_2 == 5'd16) ? 1'b1 : 1'b0);

assign trunc_ln102_fu_475_p1 = ap_sig_allocacmp_j_2[3:0];

endmodule //streaming_attention_streaming_attention_Pipeline_BETA
