-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity streaming_attention_streaming_attention_Pipeline_SCORE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tile_max_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln75 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_1 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_2 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_3 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_4 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_5 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_6 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_7 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_8 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_9 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_10 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_11 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_12 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_13 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_14 : IN STD_LOGIC_VECTOR (21 downto 0);
    sext_ln75_15 : IN STD_LOGIC_VECTOR (21 downto 0);
    score_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_15_out_ap_vld : OUT STD_LOGIC;
    score_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_14_out_ap_vld : OUT STD_LOGIC;
    score_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_13_out_ap_vld : OUT STD_LOGIC;
    score_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_12_out_ap_vld : OUT STD_LOGIC;
    score_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_11_out_ap_vld : OUT STD_LOGIC;
    score_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_10_out_ap_vld : OUT STD_LOGIC;
    score_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_9_out_ap_vld : OUT STD_LOGIC;
    score_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_8_out_ap_vld : OUT STD_LOGIC;
    score_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_7_out_ap_vld : OUT STD_LOGIC;
    score_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_6_out_ap_vld : OUT STD_LOGIC;
    score_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_5_out_ap_vld : OUT STD_LOGIC;
    score_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_4_out_ap_vld : OUT STD_LOGIC;
    score_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_3_out_ap_vld : OUT STD_LOGIC;
    score_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_2_out_ap_vld : OUT STD_LOGIC;
    score_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_1_out_ap_vld : OUT STD_LOGIC;
    score_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_out_ap_vld : OUT STD_LOGIC;
    tile_max_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tile_max_out_ap_vld : OUT STD_LOGIC;
    grp_fu_1580_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_ce : OUT STD_LOGIC );
end;


architecture behav of streaming_attention_streaming_attention_Pipeline_SCORE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_39020610 : STD_LOGIC_VECTOR (31 downto 0) := "00111001000000100000011000010000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln88_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln88_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_reg_935_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_534_p18 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln90_fu_573_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_reg_944_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_438_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_reg_948 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_max_1_reg_953 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_max_1_reg_953_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_max_load_1_reg_960 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln91_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_966 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_2_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_2_reg_976 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_3_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_3_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal tile_max_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_max_2_fu_745_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_tile_max_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_144 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln88_fu_528_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal score_fu_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_1_fu_152 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_2_fu_156 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_3_fu_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_4_fu_164 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_5_fu_168 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_6_fu_172 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_7_fu_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_8_fu_180 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_9_fu_184 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_10_fu_188 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_11_fu_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_12_fu_196 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_13_fu_200 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_14_fu_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal score_15_fu_208 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_2_fu_534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p14 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p15 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_534_p16 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln91_fu_666_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln91_1_fu_683_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_669_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln91_fu_679_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_5_fu_687_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln91_1_fu_697_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln91_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln91_1_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_1_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component streaming_attention_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component streaming_attention_sitofp_32ns_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component streaming_attention_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component streaming_attention_mux_165_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component streaming_attention_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sitofp_32ns_32_6_no_dsp_1_U283 : component streaming_attention_sitofp_32ns_32_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_2_fu_534_p18,
        ce => ap_const_logic_1,
        dout => grp_fu_438_p1);

    fcmp_32ns_32ns_1_2_no_dsp_1_U284 : component streaming_attention_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_max_1_reg_953,
        din1 => ap_sig_allocacmp_tile_max_load_1,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_441_p2);

    mux_165_32_1_1_U285 : component streaming_attention_mux_165_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_2_fu_534_p1,
        din1 => tmp_2_fu_534_p2,
        din2 => tmp_2_fu_534_p3,
        din3 => tmp_2_fu_534_p4,
        din4 => tmp_2_fu_534_p5,
        din5 => tmp_2_fu_534_p6,
        din6 => tmp_2_fu_534_p7,
        din7 => tmp_2_fu_534_p8,
        din8 => tmp_2_fu_534_p9,
        din9 => tmp_2_fu_534_p10,
        din10 => tmp_2_fu_534_p11,
        din11 => tmp_2_fu_534_p12,
        din12 => tmp_2_fu_534_p13,
        din13 => tmp_2_fu_534_p14,
        din14 => tmp_2_fu_534_p15,
        din15 => tmp_2_fu_534_p16,
        din16 => ap_sig_allocacmp_j_1,
        dout => tmp_2_fu_534_p18);

    flow_control_loop_pipe_sequential_init_U : component streaming_attention_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln88_fu_522_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_144 <= add_ln88_fu_528_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_144 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    tile_max_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    tile_max_fu_140 <= tile_max_4;
                elsif ((ap_enable_reg_pp0_iter11 = ap_const_logic_1)) then 
                    tile_max_fu_140 <= tile_max_2_fu_745_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv_reg_948 <= grp_fu_438_p1;
                icmp_ln88_reg_935_pp0_iter2_reg <= icmp_ln88_reg_935_pp0_iter1_reg;
                icmp_ln88_reg_935_pp0_iter3_reg <= icmp_ln88_reg_935_pp0_iter2_reg;
                icmp_ln88_reg_935_pp0_iter4_reg <= icmp_ln88_reg_935_pp0_iter3_reg;
                icmp_ln88_reg_935_pp0_iter5_reg <= icmp_ln88_reg_935_pp0_iter4_reg;
                icmp_ln88_reg_935_pp0_iter6_reg <= icmp_ln88_reg_935_pp0_iter5_reg;
                icmp_ln88_reg_935_pp0_iter7_reg <= icmp_ln88_reg_935_pp0_iter6_reg;
                icmp_ln88_reg_935_pp0_iter8_reg <= icmp_ln88_reg_935_pp0_iter7_reg;
                icmp_ln88_reg_935_pp0_iter9_reg <= icmp_ln88_reg_935_pp0_iter8_reg;
                icmp_ln91_1_reg_971 <= icmp_ln91_1_fu_707_p2;
                icmp_ln91_2_reg_976 <= icmp_ln91_2_fu_713_p2;
                icmp_ln91_3_reg_981 <= icmp_ln91_3_fu_719_p2;
                icmp_ln91_reg_966 <= icmp_ln91_fu_701_p2;
                tile_max_1_reg_953 <= grp_fu_1580_p_dout0;
                tile_max_1_reg_953_pp0_iter10_reg <= tile_max_1_reg_953;
                tile_max_load_1_reg_960 <= ap_sig_allocacmp_tile_max_load_1;
                trunc_ln90_reg_944_pp0_iter2_reg <= trunc_ln90_reg_944_pp0_iter1_reg;
                trunc_ln90_reg_944_pp0_iter3_reg <= trunc_ln90_reg_944_pp0_iter2_reg;
                trunc_ln90_reg_944_pp0_iter4_reg <= trunc_ln90_reg_944_pp0_iter3_reg;
                trunc_ln90_reg_944_pp0_iter5_reg <= trunc_ln90_reg_944_pp0_iter4_reg;
                trunc_ln90_reg_944_pp0_iter6_reg <= trunc_ln90_reg_944_pp0_iter5_reg;
                trunc_ln90_reg_944_pp0_iter7_reg <= trunc_ln90_reg_944_pp0_iter6_reg;
                trunc_ln90_reg_944_pp0_iter8_reg <= trunc_ln90_reg_944_pp0_iter7_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln88_reg_935 <= icmp_ln88_fu_522_p2;
                icmp_ln88_reg_935_pp0_iter1_reg <= icmp_ln88_reg_935;
                trunc_ln90_reg_944_pp0_iter1_reg <= trunc_ln90_reg_944;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_A))) then
                score_10_fu_188 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_B))) then
                score_11_fu_192 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_C))) then
                score_12_fu_196 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_D))) then
                score_13_fu_200 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_E))) then
                score_14_fu_204 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_F))) then
                score_15_fu_208 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_1))) then
                score_1_fu_152 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_2))) then
                score_2_fu_156 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_3))) then
                score_3_fu_160 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_4))) then
                score_4_fu_164 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_5))) then
                score_5_fu_168 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_6))) then
                score_6_fu_172 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_7))) then
                score_7_fu_176 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_8))) then
                score_8_fu_180 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_9))) then
                score_9_fu_184 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln90_reg_944_pp0_iter8_reg = ap_const_lv4_0))) then
                score_fu_148 <= grp_fu_1580_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln88_fu_522_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln90_reg_944 <= trunc_ln90_fu_573_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln88_fu_528_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv5_1));
    and_ln91_1_fu_739_p2 <= (grp_fu_441_p2 and and_ln91_fu_733_p2);
    and_ln91_fu_733_p2 <= (or_ln91_fu_725_p2 and or_ln91_1_fu_729_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln88_fu_522_p2)
    begin
        if (((icmp_ln88_fu_522_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_144)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_tile_max_load_1_assign_proc : process(ap_enable_reg_pp0_iter11, tile_max_fu_140, tile_max_2_fu_745_p3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            ap_sig_allocacmp_tile_max_load_1 <= tile_max_2_fu_745_p3;
        else 
            ap_sig_allocacmp_tile_max_load_1 <= tile_max_fu_140;
        end if; 
    end process;

    bitcast_ln91_1_fu_683_p1 <= ap_sig_allocacmp_tile_max_load_1;
    bitcast_ln91_fu_666_p1 <= tile_max_1_reg_953;
    grp_fu_1580_p_ce <= ap_const_logic_1;
    grp_fu_1580_p_din0 <= conv_reg_948;
    grp_fu_1580_p_din1 <= ap_const_lv32_39020610;
    icmp_ln88_fu_522_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv5_10) else "0";
    icmp_ln91_1_fu_707_p2 <= "1" when (trunc_ln91_fu_679_p1 = ap_const_lv23_0) else "0";
    icmp_ln91_2_fu_713_p2 <= "0" when (tmp_5_fu_687_p4 = ap_const_lv8_FF) else "1";
    icmp_ln91_3_fu_719_p2 <= "1" when (trunc_ln91_1_fu_697_p1 = ap_const_lv23_0) else "0";
    icmp_ln91_fu_701_p2 <= "0" when (tmp_3_fu_669_p4 = ap_const_lv8_FF) else "1";
    or_ln91_1_fu_729_p2 <= (icmp_ln91_3_reg_981 or icmp_ln91_2_reg_976);
    or_ln91_fu_725_p2 <= (icmp_ln91_reg_966 or icmp_ln91_1_reg_971);
    score_10_out <= score_10_fu_188;

    score_10_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_10_out_ap_vld <= ap_const_logic_1;
        else 
            score_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_11_out <= score_11_fu_192;

    score_11_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_11_out_ap_vld <= ap_const_logic_1;
        else 
            score_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_12_out <= score_12_fu_196;

    score_12_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_12_out_ap_vld <= ap_const_logic_1;
        else 
            score_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_13_out <= score_13_fu_200;

    score_13_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_13_out_ap_vld <= ap_const_logic_1;
        else 
            score_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_14_out <= score_14_fu_204;

    score_14_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_14_out_ap_vld <= ap_const_logic_1;
        else 
            score_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_15_out <= score_15_fu_208;

    score_15_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_15_out_ap_vld <= ap_const_logic_1;
        else 
            score_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_1_out <= score_1_fu_152;

    score_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_1_out_ap_vld <= ap_const_logic_1;
        else 
            score_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_2_out <= score_2_fu_156;

    score_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_2_out_ap_vld <= ap_const_logic_1;
        else 
            score_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_3_out <= score_3_fu_160;

    score_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_3_out_ap_vld <= ap_const_logic_1;
        else 
            score_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_4_out <= score_4_fu_164;

    score_4_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_4_out_ap_vld <= ap_const_logic_1;
        else 
            score_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_5_out <= score_5_fu_168;

    score_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_5_out_ap_vld <= ap_const_logic_1;
        else 
            score_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_6_out <= score_6_fu_172;

    score_6_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_6_out_ap_vld <= ap_const_logic_1;
        else 
            score_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_7_out <= score_7_fu_176;

    score_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_7_out_ap_vld <= ap_const_logic_1;
        else 
            score_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_8_out <= score_8_fu_180;

    score_8_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_8_out_ap_vld <= ap_const_logic_1;
        else 
            score_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_9_out <= score_9_fu_184;

    score_9_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_9_out_ap_vld <= ap_const_logic_1;
        else 
            score_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    score_out <= score_fu_148;

    score_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            score_out_ap_vld <= ap_const_logic_1;
        else 
            score_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tile_max_2_fu_745_p3 <= 
        tile_max_1_reg_953_pp0_iter10_reg when (and_ln91_1_fu_739_p2(0) = '1') else 
        tile_max_load_1_reg_960;
    tile_max_out <= tile_max_fu_140;

    tile_max_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln88_reg_935_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln88_reg_935_pp0_iter9_reg = ap_const_lv1_1))) then 
            tile_max_out_ap_vld <= ap_const_logic_1;
        else 
            tile_max_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        tmp_2_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75),32));

        tmp_2_fu_534_p10 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_9),32));

        tmp_2_fu_534_p11 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_10),32));

        tmp_2_fu_534_p12 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_11),32));

        tmp_2_fu_534_p13 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_12),32));

        tmp_2_fu_534_p14 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_13),32));

        tmp_2_fu_534_p15 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_14),32));

        tmp_2_fu_534_p16 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_15),32));

        tmp_2_fu_534_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_1),32));

        tmp_2_fu_534_p3 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_2),32));

        tmp_2_fu_534_p4 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_3),32));

        tmp_2_fu_534_p5 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_4),32));

        tmp_2_fu_534_p6 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_5),32));

        tmp_2_fu_534_p7 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_6),32));

        tmp_2_fu_534_p8 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_7),32));

        tmp_2_fu_534_p9 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln75_8),32));

    tmp_3_fu_669_p4 <= bitcast_ln91_fu_666_p1(30 downto 23);
    tmp_5_fu_687_p4 <= bitcast_ln91_1_fu_683_p1(30 downto 23);
    trunc_ln90_fu_573_p1 <= ap_sig_allocacmp_j_1(4 - 1 downto 0);
    trunc_ln91_1_fu_697_p1 <= bitcast_ln91_1_fu_683_p1(23 - 1 downto 0);
    trunc_ln91_fu_679_p1 <= bitcast_ln91_fu_666_p1(23 - 1 downto 0);
end behav;
