# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.srcs/sources_1/bd/design_1/ip/design_1_hp_sc_0/design_1_hp_sc_0.xci
# IP: The module: 'design_1_hp_sc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/bd_a154.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_0/bd_a154_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_2/bd_a154_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_3/bd_a154_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_4/bd_a154_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_5/bd_a154_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_6/bd_a154_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_7/bd_a154_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_8/bd_a154_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_9/bd_a154_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_10/bd_a154_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_11/bd_a154_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_12/bd_a154_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_13/bd_a154_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_14/bd_a154_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_15/bd_a154_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_16/bd_a154_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_17/bd_a154_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_18/bd_a154_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_19/bd_a154_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_20/bd_a154_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_21/bd_a154_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_22/bd_a154_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_23/bd_a154_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_24/bd_a154_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_25/bd_a154_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_26/bd_a154_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_27/bd_a154_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_28/bd_a154_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_29/bd_a154_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_30/bd_a154_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_31/bd_a154_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_32/bd_a154_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_33/bd_a154_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_34/bd_a154_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_35/bd_a154_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_36/bd_a154_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_37/bd_a154_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_38/bd_a154_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_2/bd_a154_arsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_3/bd_a154_rsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_4/bd_a154_awsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_5/bd_a154_wsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_6/bd_a154_bsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_10/bd_a154_s00a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_11/bd_a154_sarn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_12/bd_a154_srn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_16/bd_a154_s01a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_17/bd_a154_sarn_1_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_18/bd_a154_srn_1_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_22/bd_a154_s02a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_23/bd_a154_sarn_2_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_24/bd_a154_srn_2_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_28/bd_a154_s03a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_29/bd_a154_sawn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_30/bd_a154_swn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_31/bd_a154_sbn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_32/bd_a154_m00s2a_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_33/bd_a154_m00arn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_34/bd_a154_m00rn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_35/bd_a154_m00awn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_36/bd_a154_m00wn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_37/bd_a154_m00bn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hp_sc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.srcs/sources_1/bd/design_1/ip/design_1_hp_sc_0/design_1_hp_sc_0.xci
# IP: The module: 'design_1_hp_sc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/bd_a154.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_0/bd_a154_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_2/bd_a154_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_3/bd_a154_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_4/bd_a154_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_5/bd_a154_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_6/bd_a154_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_7/bd_a154_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_8/bd_a154_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_9/bd_a154_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_10/bd_a154_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_11/bd_a154_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_12/bd_a154_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_13/bd_a154_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_14/bd_a154_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_15/bd_a154_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_16/bd_a154_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_17/bd_a154_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_18/bd_a154_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_19/bd_a154_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_20/bd_a154_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_21/bd_a154_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_22/bd_a154_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_23/bd_a154_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_24/bd_a154_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_25/bd_a154_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_26/bd_a154_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_27/bd_a154_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_28/bd_a154_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_29/bd_a154_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_30/bd_a154_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_31/bd_a154_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_32/bd_a154_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_33/bd_a154_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_34/bd_a154_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_35/bd_a154_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_36/bd_a154_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_37/bd_a154_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_38/bd_a154_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_1/bd_a154_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_2/bd_a154_arsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_3/bd_a154_rsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_4/bd_a154_awsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_5/bd_a154_wsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_6/bd_a154_bsw_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_10/bd_a154_s00a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_11/bd_a154_sarn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_12/bd_a154_srn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_16/bd_a154_s01a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_17/bd_a154_sarn_1_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_18/bd_a154_srn_1_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_22/bd_a154_s02a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_23/bd_a154_sarn_2_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_24/bd_a154_srn_2_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_28/bd_a154_s03a2s_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_29/bd_a154_sawn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_30/bd_a154_swn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_31/bd_a154_sbn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_32/bd_a154_m00s2a_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_33/bd_a154_m00arn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_34/bd_a154_m00rn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_35/bd_a154_m00awn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_36/bd_a154_m00wn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/bd_0/ip/ip_37/bd_a154_m00bn_0_ooc.xdc

# XDC: /home/users/andgiuri/softmax-accelerator/stream_attn/vivado/attn_z2/attn_z2.gen/sources_1/bd/design_1/ip/design_1_hp_sc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_hp_sc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
