-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity streaming_attention_streaming_attention_Pipeline_LOAD_TILE_VITIS_LOOP_59_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln54 : IN STD_LOGIC_VECTOR (63 downto 0);
    add_ln54_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    vt_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_ce0 : OUT STD_LOGIC;
    vt_we0 : OUT STD_LOGIC;
    vt_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_ce0 : OUT STD_LOGIC;
    kt_we0 : OUT STD_LOGIC;
    kt_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_1_ce0 : OUT STD_LOGIC;
    kt_1_we0 : OUT STD_LOGIC;
    kt_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_2_ce0 : OUT STD_LOGIC;
    kt_2_we0 : OUT STD_LOGIC;
    kt_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_3_ce0 : OUT STD_LOGIC;
    kt_3_we0 : OUT STD_LOGIC;
    kt_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_4_ce0 : OUT STD_LOGIC;
    kt_4_we0 : OUT STD_LOGIC;
    kt_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_5_ce0 : OUT STD_LOGIC;
    kt_5_we0 : OUT STD_LOGIC;
    kt_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_6_ce0 : OUT STD_LOGIC;
    kt_6_we0 : OUT STD_LOGIC;
    kt_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_7_ce0 : OUT STD_LOGIC;
    kt_7_we0 : OUT STD_LOGIC;
    kt_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_8_ce0 : OUT STD_LOGIC;
    kt_8_we0 : OUT STD_LOGIC;
    kt_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_9_ce0 : OUT STD_LOGIC;
    kt_9_we0 : OUT STD_LOGIC;
    kt_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_10_ce0 : OUT STD_LOGIC;
    kt_10_we0 : OUT STD_LOGIC;
    kt_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_11_ce0 : OUT STD_LOGIC;
    kt_11_we0 : OUT STD_LOGIC;
    kt_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_12_ce0 : OUT STD_LOGIC;
    kt_12_we0 : OUT STD_LOGIC;
    kt_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_13_ce0 : OUT STD_LOGIC;
    kt_13_we0 : OUT STD_LOGIC;
    kt_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_14_ce0 : OUT STD_LOGIC;
    kt_14_we0 : OUT STD_LOGIC;
    kt_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    kt_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    kt_15_ce0 : OUT STD_LOGIC;
    kt_15_we0 : OUT STD_LOGIC;
    kt_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_1_ce0 : OUT STD_LOGIC;
    vt_1_we0 : OUT STD_LOGIC;
    vt_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_2_ce0 : OUT STD_LOGIC;
    vt_2_we0 : OUT STD_LOGIC;
    vt_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_3_ce0 : OUT STD_LOGIC;
    vt_3_we0 : OUT STD_LOGIC;
    vt_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_4_ce0 : OUT STD_LOGIC;
    vt_4_we0 : OUT STD_LOGIC;
    vt_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_5_ce0 : OUT STD_LOGIC;
    vt_5_we0 : OUT STD_LOGIC;
    vt_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_6_ce0 : OUT STD_LOGIC;
    vt_6_we0 : OUT STD_LOGIC;
    vt_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_7_ce0 : OUT STD_LOGIC;
    vt_7_we0 : OUT STD_LOGIC;
    vt_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_8_ce0 : OUT STD_LOGIC;
    vt_8_we0 : OUT STD_LOGIC;
    vt_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_9_ce0 : OUT STD_LOGIC;
    vt_9_we0 : OUT STD_LOGIC;
    vt_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_10_ce0 : OUT STD_LOGIC;
    vt_10_we0 : OUT STD_LOGIC;
    vt_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_11_ce0 : OUT STD_LOGIC;
    vt_11_we0 : OUT STD_LOGIC;
    vt_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_12_ce0 : OUT STD_LOGIC;
    vt_12_we0 : OUT STD_LOGIC;
    vt_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_13_ce0 : OUT STD_LOGIC;
    vt_13_we0 : OUT STD_LOGIC;
    vt_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_14_ce0 : OUT STD_LOGIC;
    vt_14_we0 : OUT STD_LOGIC;
    vt_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    vt_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    vt_15_ce0 : OUT STD_LOGIC;
    vt_15_we0 : OUT STD_LOGIC;
    vt_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of streaming_attention_streaming_attention_Pipeline_LOAD_TILE_VITIS_LOOP_59_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln58_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal gmem1_addr_read_reg_782 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem2_addr_read_reg_802 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln59_fu_695_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln58_fu_691_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_160 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_fu_731_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_164 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln58_1_fu_683_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_168 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_fu_646_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln59_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln58_1_fu_677_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln58_fu_669_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component streaming_attention_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component streaming_attention_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    d_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    d_fu_160 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    d_fu_160 <= add_ln59_fu_731_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln58_fu_640_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_168 <= add_ln58_fu_646_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_168 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    j_fu_164 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    j_fu_164 <= select_ln58_1_fu_683_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                gmem1_addr_read_reg_782 <= m_axi_gmem1_RDATA;
                gmem2_addr_read_reg_802 <= m_axi_gmem2_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_1_fu_677_p2 <= std_logic_vector(unsigned(j_fu_164) + unsigned(ap_const_lv5_1));
    add_ln58_fu_646_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv11_1));
    add_ln59_fu_731_p2 <= std_logic_vector(unsigned(select_ln58_fu_669_p3) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, m_axi_gmem2_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axi_gmem1_RVALID = ap_const_logic_0) or (m_axi_gmem2_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, m_axi_gmem2_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axi_gmem1_RVALID = ap_const_logic_0) or (m_axi_gmem2_RVALID = ap_const_logic_0)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem1_RVALID, m_axi_gmem2_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((m_axi_gmem1_RVALID = ap_const_logic_0) or (m_axi_gmem2_RVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln58_fu_640_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln58_fu_640_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_168)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_168;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem2_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem2_blk_n_R <= m_axi_gmem2_RVALID;
        else 
            gmem2_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln58_fu_640_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv11_400) else "0";
    icmp_ln59_fu_663_p2 <= "1" when (d_fu_160 = ap_const_lv7_40) else "0";
    kt_10_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_10_ce0 <= ap_const_logic_1;
        else 
            kt_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_10_d0 <= gmem1_addr_read_reg_782;

    kt_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_10_we0 <= ap_const_logic_1;
        else 
            kt_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_11_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_11_ce0 <= ap_const_logic_1;
        else 
            kt_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_11_d0 <= gmem1_addr_read_reg_782;

    kt_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_11_we0 <= ap_const_logic_1;
        else 
            kt_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_12_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_12_ce0 <= ap_const_logic_1;
        else 
            kt_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_12_d0 <= gmem1_addr_read_reg_782;

    kt_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_12_we0 <= ap_const_logic_1;
        else 
            kt_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_13_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_13_ce0 <= ap_const_logic_1;
        else 
            kt_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_13_d0 <= gmem1_addr_read_reg_782;

    kt_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_13_we0 <= ap_const_logic_1;
        else 
            kt_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_14_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_14_ce0 <= ap_const_logic_1;
        else 
            kt_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_14_d0 <= gmem1_addr_read_reg_782;

    kt_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_14_we0 <= ap_const_logic_1;
        else 
            kt_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_15_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_15_ce0 <= ap_const_logic_1;
        else 
            kt_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_15_d0 <= gmem1_addr_read_reg_782;

    kt_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_15_we0 <= ap_const_logic_1;
        else 
            kt_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_1_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_1_ce0 <= ap_const_logic_1;
        else 
            kt_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_1_d0 <= gmem1_addr_read_reg_782;

    kt_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_1_we0 <= ap_const_logic_1;
        else 
            kt_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_2_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_2_ce0 <= ap_const_logic_1;
        else 
            kt_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_2_d0 <= gmem1_addr_read_reg_782;

    kt_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_2_we0 <= ap_const_logic_1;
        else 
            kt_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_3_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_3_ce0 <= ap_const_logic_1;
        else 
            kt_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_3_d0 <= gmem1_addr_read_reg_782;

    kt_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_3_we0 <= ap_const_logic_1;
        else 
            kt_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_4_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_4_ce0 <= ap_const_logic_1;
        else 
            kt_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_4_d0 <= gmem1_addr_read_reg_782;

    kt_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_4_we0 <= ap_const_logic_1;
        else 
            kt_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_5_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_5_ce0 <= ap_const_logic_1;
        else 
            kt_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_5_d0 <= gmem1_addr_read_reg_782;

    kt_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_5_we0 <= ap_const_logic_1;
        else 
            kt_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_6_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_6_ce0 <= ap_const_logic_1;
        else 
            kt_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_6_d0 <= gmem1_addr_read_reg_782;

    kt_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_6_we0 <= ap_const_logic_1;
        else 
            kt_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_7_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_7_ce0 <= ap_const_logic_1;
        else 
            kt_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_7_d0 <= gmem1_addr_read_reg_782;

    kt_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_7_we0 <= ap_const_logic_1;
        else 
            kt_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_8_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_8_ce0 <= ap_const_logic_1;
        else 
            kt_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_8_d0 <= gmem1_addr_read_reg_782;

    kt_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_8_we0 <= ap_const_logic_1;
        else 
            kt_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_9_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_9_ce0 <= ap_const_logic_1;
        else 
            kt_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_9_d0 <= gmem1_addr_read_reg_782;

    kt_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_9_we0 <= ap_const_logic_1;
        else 
            kt_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    kt_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_ce0 <= ap_const_logic_1;
        else 
            kt_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kt_d0 <= gmem1_addr_read_reg_782;

    kt_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            kt_we0 <= ap_const_logic_1;
        else 
            kt_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv8_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv1_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    m_axi_gmem2_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_ARID <= ap_const_lv1_0;
    m_axi_gmem2_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_AWID <= ap_const_lv1_0;
    m_axi_gmem2_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_BREADY <= ap_const_logic_0;

    m_axi_gmem2_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem2_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem2_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_WDATA <= ap_const_lv8_0;
    m_axi_gmem2_WID <= ap_const_lv1_0;
    m_axi_gmem2_WLAST <= ap_const_logic_0;
    m_axi_gmem2_WSTRB <= ap_const_lv1_0;
    m_axi_gmem2_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_WVALID <= ap_const_logic_0;
    select_ln58_1_fu_683_p3 <= 
        add_ln58_1_fu_677_p2 when (icmp_ln59_fu_663_p2(0) = '1') else 
        j_fu_164;
    select_ln58_fu_669_p3 <= 
        ap_const_lv7_0 when (icmp_ln59_fu_663_p2(0) = '1') else 
        d_fu_160;
    trunc_ln58_fu_691_p1 <= select_ln58_1_fu_683_p3(4 - 1 downto 0);
    vt_10_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_10_ce0 <= ap_const_logic_1;
        else 
            vt_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_10_d0 <= gmem2_addr_read_reg_802;

    vt_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_10_we0 <= ap_const_logic_1;
        else 
            vt_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_11_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_11_ce0 <= ap_const_logic_1;
        else 
            vt_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_11_d0 <= gmem2_addr_read_reg_802;

    vt_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_11_we0 <= ap_const_logic_1;
        else 
            vt_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_12_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_12_ce0 <= ap_const_logic_1;
        else 
            vt_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_12_d0 <= gmem2_addr_read_reg_802;

    vt_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_12_we0 <= ap_const_logic_1;
        else 
            vt_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_13_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_13_ce0 <= ap_const_logic_1;
        else 
            vt_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_13_d0 <= gmem2_addr_read_reg_802;

    vt_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_13_we0 <= ap_const_logic_1;
        else 
            vt_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_14_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_14_ce0 <= ap_const_logic_1;
        else 
            vt_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_14_d0 <= gmem2_addr_read_reg_802;

    vt_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_14_we0 <= ap_const_logic_1;
        else 
            vt_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_15_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_15_ce0 <= ap_const_logic_1;
        else 
            vt_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_15_d0 <= gmem2_addr_read_reg_802;

    vt_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_15_we0 <= ap_const_logic_1;
        else 
            vt_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_1_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_1_ce0 <= ap_const_logic_1;
        else 
            vt_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_1_d0 <= gmem2_addr_read_reg_802;

    vt_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_1_we0 <= ap_const_logic_1;
        else 
            vt_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_2_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_2_ce0 <= ap_const_logic_1;
        else 
            vt_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_2_d0 <= gmem2_addr_read_reg_802;

    vt_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_2_we0 <= ap_const_logic_1;
        else 
            vt_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_3_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_3_ce0 <= ap_const_logic_1;
        else 
            vt_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_3_d0 <= gmem2_addr_read_reg_802;

    vt_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_3_we0 <= ap_const_logic_1;
        else 
            vt_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_4_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_4_ce0 <= ap_const_logic_1;
        else 
            vt_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_4_d0 <= gmem2_addr_read_reg_802;

    vt_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_4_we0 <= ap_const_logic_1;
        else 
            vt_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_5_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_5_ce0 <= ap_const_logic_1;
        else 
            vt_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_5_d0 <= gmem2_addr_read_reg_802;

    vt_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_5_we0 <= ap_const_logic_1;
        else 
            vt_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_6_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_6_ce0 <= ap_const_logic_1;
        else 
            vt_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_6_d0 <= gmem2_addr_read_reg_802;

    vt_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_6_we0 <= ap_const_logic_1;
        else 
            vt_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_7_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_7_ce0 <= ap_const_logic_1;
        else 
            vt_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_7_d0 <= gmem2_addr_read_reg_802;

    vt_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_7_we0 <= ap_const_logic_1;
        else 
            vt_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_8_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_8_ce0 <= ap_const_logic_1;
        else 
            vt_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_8_d0 <= gmem2_addr_read_reg_802;

    vt_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_8_we0 <= ap_const_logic_1;
        else 
            vt_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_9_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_9_ce0 <= ap_const_logic_1;
        else 
            vt_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_9_d0 <= gmem2_addr_read_reg_802;

    vt_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_9_we0 <= ap_const_logic_1;
        else 
            vt_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_address0 <= zext_ln59_fu_695_p1(6 - 1 downto 0);

    vt_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_ce0 <= ap_const_logic_1;
        else 
            vt_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    vt_d0 <= gmem2_addr_read_reg_802;

    vt_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln58_fu_691_p1)
    begin
        if (((trunc_ln58_fu_691_p1 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            vt_we0 <= ap_const_logic_1;
        else 
            vt_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln59_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln58_fu_669_p3),64));
end behav;
