// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module streaming_attention_streaming_attention_Pipeline_LOAD_TILE_VITIS_LOOP_59_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        add_ln54,
        add_ln54_1,
        vt_address0,
        vt_ce0,
        vt_we0,
        vt_d0,
        kt_address0,
        kt_ce0,
        kt_we0,
        kt_d0,
        kt_1_address0,
        kt_1_ce0,
        kt_1_we0,
        kt_1_d0,
        kt_2_address0,
        kt_2_ce0,
        kt_2_we0,
        kt_2_d0,
        kt_3_address0,
        kt_3_ce0,
        kt_3_we0,
        kt_3_d0,
        kt_4_address0,
        kt_4_ce0,
        kt_4_we0,
        kt_4_d0,
        kt_5_address0,
        kt_5_ce0,
        kt_5_we0,
        kt_5_d0,
        kt_6_address0,
        kt_6_ce0,
        kt_6_we0,
        kt_6_d0,
        kt_7_address0,
        kt_7_ce0,
        kt_7_we0,
        kt_7_d0,
        kt_8_address0,
        kt_8_ce0,
        kt_8_we0,
        kt_8_d0,
        kt_9_address0,
        kt_9_ce0,
        kt_9_we0,
        kt_9_d0,
        kt_10_address0,
        kt_10_ce0,
        kt_10_we0,
        kt_10_d0,
        kt_11_address0,
        kt_11_ce0,
        kt_11_we0,
        kt_11_d0,
        kt_12_address0,
        kt_12_ce0,
        kt_12_we0,
        kt_12_d0,
        kt_13_address0,
        kt_13_ce0,
        kt_13_we0,
        kt_13_d0,
        kt_14_address0,
        kt_14_ce0,
        kt_14_we0,
        kt_14_d0,
        kt_15_address0,
        kt_15_ce0,
        kt_15_we0,
        kt_15_d0,
        vt_1_address0,
        vt_1_ce0,
        vt_1_we0,
        vt_1_d0,
        vt_2_address0,
        vt_2_ce0,
        vt_2_we0,
        vt_2_d0,
        vt_3_address0,
        vt_3_ce0,
        vt_3_we0,
        vt_3_d0,
        vt_4_address0,
        vt_4_ce0,
        vt_4_we0,
        vt_4_d0,
        vt_5_address0,
        vt_5_ce0,
        vt_5_we0,
        vt_5_d0,
        vt_6_address0,
        vt_6_ce0,
        vt_6_we0,
        vt_6_d0,
        vt_7_address0,
        vt_7_ce0,
        vt_7_we0,
        vt_7_d0,
        vt_8_address0,
        vt_8_ce0,
        vt_8_we0,
        vt_8_d0,
        vt_9_address0,
        vt_9_ce0,
        vt_9_we0,
        vt_9_d0,
        vt_10_address0,
        vt_10_ce0,
        vt_10_we0,
        vt_10_d0,
        vt_11_address0,
        vt_11_ce0,
        vt_11_we0,
        vt_11_d0,
        vt_12_address0,
        vt_12_ce0,
        vt_12_we0,
        vt_12_d0,
        vt_13_address0,
        vt_13_ce0,
        vt_13_we0,
        vt_13_d0,
        vt_14_address0,
        vt_14_ce0,
        vt_14_we0,
        vt_14_d0,
        vt_15_address0,
        vt_15_ce0,
        vt_15_we0,
        vt_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [7:0] m_axi_gmem2_WDATA;
output  [0:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [7:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [10:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] add_ln54;
input  [63:0] add_ln54_1;
output  [5:0] vt_address0;
output   vt_ce0;
output   vt_we0;
output  [7:0] vt_d0;
output  [5:0] kt_address0;
output   kt_ce0;
output   kt_we0;
output  [7:0] kt_d0;
output  [5:0] kt_1_address0;
output   kt_1_ce0;
output   kt_1_we0;
output  [7:0] kt_1_d0;
output  [5:0] kt_2_address0;
output   kt_2_ce0;
output   kt_2_we0;
output  [7:0] kt_2_d0;
output  [5:0] kt_3_address0;
output   kt_3_ce0;
output   kt_3_we0;
output  [7:0] kt_3_d0;
output  [5:0] kt_4_address0;
output   kt_4_ce0;
output   kt_4_we0;
output  [7:0] kt_4_d0;
output  [5:0] kt_5_address0;
output   kt_5_ce0;
output   kt_5_we0;
output  [7:0] kt_5_d0;
output  [5:0] kt_6_address0;
output   kt_6_ce0;
output   kt_6_we0;
output  [7:0] kt_6_d0;
output  [5:0] kt_7_address0;
output   kt_7_ce0;
output   kt_7_we0;
output  [7:0] kt_7_d0;
output  [5:0] kt_8_address0;
output   kt_8_ce0;
output   kt_8_we0;
output  [7:0] kt_8_d0;
output  [5:0] kt_9_address0;
output   kt_9_ce0;
output   kt_9_we0;
output  [7:0] kt_9_d0;
output  [5:0] kt_10_address0;
output   kt_10_ce0;
output   kt_10_we0;
output  [7:0] kt_10_d0;
output  [5:0] kt_11_address0;
output   kt_11_ce0;
output   kt_11_we0;
output  [7:0] kt_11_d0;
output  [5:0] kt_12_address0;
output   kt_12_ce0;
output   kt_12_we0;
output  [7:0] kt_12_d0;
output  [5:0] kt_13_address0;
output   kt_13_ce0;
output   kt_13_we0;
output  [7:0] kt_13_d0;
output  [5:0] kt_14_address0;
output   kt_14_ce0;
output   kt_14_we0;
output  [7:0] kt_14_d0;
output  [5:0] kt_15_address0;
output   kt_15_ce0;
output   kt_15_we0;
output  [7:0] kt_15_d0;
output  [5:0] vt_1_address0;
output   vt_1_ce0;
output   vt_1_we0;
output  [7:0] vt_1_d0;
output  [5:0] vt_2_address0;
output   vt_2_ce0;
output   vt_2_we0;
output  [7:0] vt_2_d0;
output  [5:0] vt_3_address0;
output   vt_3_ce0;
output   vt_3_we0;
output  [7:0] vt_3_d0;
output  [5:0] vt_4_address0;
output   vt_4_ce0;
output   vt_4_we0;
output  [7:0] vt_4_d0;
output  [5:0] vt_5_address0;
output   vt_5_ce0;
output   vt_5_we0;
output  [7:0] vt_5_d0;
output  [5:0] vt_6_address0;
output   vt_6_ce0;
output   vt_6_we0;
output  [7:0] vt_6_d0;
output  [5:0] vt_7_address0;
output   vt_7_ce0;
output   vt_7_we0;
output  [7:0] vt_7_d0;
output  [5:0] vt_8_address0;
output   vt_8_ce0;
output   vt_8_we0;
output  [7:0] vt_8_d0;
output  [5:0] vt_9_address0;
output   vt_9_ce0;
output   vt_9_we0;
output  [7:0] vt_9_d0;
output  [5:0] vt_10_address0;
output   vt_10_ce0;
output   vt_10_we0;
output  [7:0] vt_10_d0;
output  [5:0] vt_11_address0;
output   vt_11_ce0;
output   vt_11_we0;
output  [7:0] vt_11_d0;
output  [5:0] vt_12_address0;
output   vt_12_ce0;
output   vt_12_we0;
output  [7:0] vt_12_d0;
output  [5:0] vt_13_address0;
output   vt_13_ce0;
output   vt_13_we0;
output  [7:0] vt_13_d0;
output  [5:0] vt_14_address0;
output   vt_14_ce0;
output   vt_14_we0;
output  [7:0] vt_14_d0;
output  [5:0] vt_15_address0;
output   vt_15_ce0;
output   vt_15_we0;
output  [7:0] vt_15_d0;

reg ap_idle;
reg m_axi_gmem1_RREADY;
reg m_axi_gmem2_RREADY;
reg vt_ce0;
reg vt_we0;
reg kt_ce0;
reg kt_we0;
reg kt_1_ce0;
reg kt_1_we0;
reg kt_2_ce0;
reg kt_2_we0;
reg kt_3_ce0;
reg kt_3_we0;
reg kt_4_ce0;
reg kt_4_we0;
reg kt_5_ce0;
reg kt_5_we0;
reg kt_6_ce0;
reg kt_6_we0;
reg kt_7_ce0;
reg kt_7_we0;
reg kt_8_ce0;
reg kt_8_we0;
reg kt_9_ce0;
reg kt_9_we0;
reg kt_10_ce0;
reg kt_10_we0;
reg kt_11_ce0;
reg kt_11_we0;
reg kt_12_ce0;
reg kt_12_we0;
reg kt_13_ce0;
reg kt_13_we0;
reg kt_14_ce0;
reg kt_14_we0;
reg kt_15_ce0;
reg kt_15_we0;
reg vt_1_ce0;
reg vt_1_we0;
reg vt_2_ce0;
reg vt_2_we0;
reg vt_3_ce0;
reg vt_3_we0;
reg vt_4_ce0;
reg vt_4_we0;
reg vt_5_ce0;
reg vt_5_we0;
reg vt_6_ce0;
reg vt_6_we0;
reg vt_7_ce0;
reg vt_7_we0;
reg vt_8_ce0;
reg vt_8_we0;
reg vt_9_ce0;
reg vt_9_we0;
reg vt_10_ce0;
reg vt_10_we0;
reg vt_11_ce0;
reg vt_11_we0;
reg vt_12_ce0;
reg vt_12_we0;
reg vt_13_ce0;
reg vt_13_we0;
reg vt_14_ce0;
reg vt_14_we0;
reg vt_15_ce0;
reg vt_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_640_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem2_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_R;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] gmem1_addr_read_reg_782;
reg   [7:0] gmem2_addr_read_reg_802;
wire   [63:0] zext_ln59_fu_695_p1;
wire   [3:0] trunc_ln58_fu_691_p1;
reg   [6:0] d_fu_160;
wire   [6:0] add_ln59_fu_731_p2;
wire    ap_loop_init;
reg   [4:0] j_fu_164;
wire   [4:0] select_ln58_1_fu_683_p3;
reg   [10:0] indvar_flatten_fu_168;
wire   [10:0] add_ln58_fu_646_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln59_fu_663_p2;
wire   [4:0] add_ln58_1_fu_677_p2;
wire   [6:0] select_ln58_fu_669_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

streaming_attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            d_fu_160 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            d_fu_160 <= add_ln59_fu_731_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln58_fu_640_p2 == 1'd0))) begin
            indvar_flatten_fu_168 <= add_ln58_fu_646_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_168 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            j_fu_164 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j_fu_164 <= select_ln58_1_fu_683_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        gmem1_addr_read_reg_782 <= m_axi_gmem1_RDATA;
        gmem2_addr_read_reg_802 <= m_axi_gmem2_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln58_fu_640_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_168;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem2_blk_n_R = m_axi_gmem2_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_10_ce0 = 1'b1;
    end else begin
        kt_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd10) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_10_we0 = 1'b1;
    end else begin
        kt_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_11_ce0 = 1'b1;
    end else begin
        kt_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_11_we0 = 1'b1;
    end else begin
        kt_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_12_ce0 = 1'b1;
    end else begin
        kt_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd12) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_12_we0 = 1'b1;
    end else begin
        kt_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_13_ce0 = 1'b1;
    end else begin
        kt_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd13) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_13_we0 = 1'b1;
    end else begin
        kt_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_14_ce0 = 1'b1;
    end else begin
        kt_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd14) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_14_we0 = 1'b1;
    end else begin
        kt_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_15_ce0 = 1'b1;
    end else begin
        kt_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_15_we0 = 1'b1;
    end else begin
        kt_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_1_ce0 = 1'b1;
    end else begin
        kt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_1_we0 = 1'b1;
    end else begin
        kt_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_2_ce0 = 1'b1;
    end else begin
        kt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_2_we0 = 1'b1;
    end else begin
        kt_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_3_ce0 = 1'b1;
    end else begin
        kt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_3_we0 = 1'b1;
    end else begin
        kt_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_4_ce0 = 1'b1;
    end else begin
        kt_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_4_we0 = 1'b1;
    end else begin
        kt_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_5_ce0 = 1'b1;
    end else begin
        kt_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_5_we0 = 1'b1;
    end else begin
        kt_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_6_ce0 = 1'b1;
    end else begin
        kt_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_6_we0 = 1'b1;
    end else begin
        kt_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_7_ce0 = 1'b1;
    end else begin
        kt_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_7_we0 = 1'b1;
    end else begin
        kt_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_8_ce0 = 1'b1;
    end else begin
        kt_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd8) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_8_we0 = 1'b1;
    end else begin
        kt_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_9_ce0 = 1'b1;
    end else begin
        kt_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_9_we0 = 1'b1;
    end else begin
        kt_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_ce0 = 1'b1;
    end else begin
        kt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kt_we0 = 1'b1;
    end else begin
        kt_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem2_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_10_ce0 = 1'b1;
    end else begin
        vt_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd10) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_10_we0 = 1'b1;
    end else begin
        vt_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_11_ce0 = 1'b1;
    end else begin
        vt_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_11_we0 = 1'b1;
    end else begin
        vt_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_12_ce0 = 1'b1;
    end else begin
        vt_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd12) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_12_we0 = 1'b1;
    end else begin
        vt_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_13_ce0 = 1'b1;
    end else begin
        vt_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd13) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_13_we0 = 1'b1;
    end else begin
        vt_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_14_ce0 = 1'b1;
    end else begin
        vt_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd14) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_14_we0 = 1'b1;
    end else begin
        vt_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_15_ce0 = 1'b1;
    end else begin
        vt_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_15_we0 = 1'b1;
    end else begin
        vt_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_1_ce0 = 1'b1;
    end else begin
        vt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_1_we0 = 1'b1;
    end else begin
        vt_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_2_ce0 = 1'b1;
    end else begin
        vt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_2_we0 = 1'b1;
    end else begin
        vt_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_3_ce0 = 1'b1;
    end else begin
        vt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_3_we0 = 1'b1;
    end else begin
        vt_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_4_ce0 = 1'b1;
    end else begin
        vt_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_4_we0 = 1'b1;
    end else begin
        vt_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_5_ce0 = 1'b1;
    end else begin
        vt_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_5_we0 = 1'b1;
    end else begin
        vt_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_6_ce0 = 1'b1;
    end else begin
        vt_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_6_we0 = 1'b1;
    end else begin
        vt_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_7_ce0 = 1'b1;
    end else begin
        vt_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_7_we0 = 1'b1;
    end else begin
        vt_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_8_ce0 = 1'b1;
    end else begin
        vt_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd8) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_8_we0 = 1'b1;
    end else begin
        vt_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_9_ce0 = 1'b1;
    end else begin
        vt_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_9_we0 = 1'b1;
    end else begin
        vt_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_ce0 = 1'b1;
    end else begin
        vt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_fu_691_p1 == 4'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        vt_we0 = 1'b1;
    end else begin
        vt_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_1_fu_677_p2 = (j_fu_164 + 5'd1);

assign add_ln58_fu_646_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln59_fu_731_p2 = (select_ln58_fu_669_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem1_RVALID == 1'b0) | (m_axi_gmem2_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((m_axi_gmem1_RVALID == 1'b0) | (m_axi_gmem2_RVALID == 1'b0)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((m_axi_gmem1_RVALID == 1'b0) | (m_axi_gmem2_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln58_fu_640_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_663_p2 = ((d_fu_160 == 7'd64) ? 1'b1 : 1'b0);

assign kt_10_address0 = zext_ln59_fu_695_p1;

assign kt_10_d0 = gmem1_addr_read_reg_782;

assign kt_11_address0 = zext_ln59_fu_695_p1;

assign kt_11_d0 = gmem1_addr_read_reg_782;

assign kt_12_address0 = zext_ln59_fu_695_p1;

assign kt_12_d0 = gmem1_addr_read_reg_782;

assign kt_13_address0 = zext_ln59_fu_695_p1;

assign kt_13_d0 = gmem1_addr_read_reg_782;

assign kt_14_address0 = zext_ln59_fu_695_p1;

assign kt_14_d0 = gmem1_addr_read_reg_782;

assign kt_15_address0 = zext_ln59_fu_695_p1;

assign kt_15_d0 = gmem1_addr_read_reg_782;

assign kt_1_address0 = zext_ln59_fu_695_p1;

assign kt_1_d0 = gmem1_addr_read_reg_782;

assign kt_2_address0 = zext_ln59_fu_695_p1;

assign kt_2_d0 = gmem1_addr_read_reg_782;

assign kt_3_address0 = zext_ln59_fu_695_p1;

assign kt_3_d0 = gmem1_addr_read_reg_782;

assign kt_4_address0 = zext_ln59_fu_695_p1;

assign kt_4_d0 = gmem1_addr_read_reg_782;

assign kt_5_address0 = zext_ln59_fu_695_p1;

assign kt_5_d0 = gmem1_addr_read_reg_782;

assign kt_6_address0 = zext_ln59_fu_695_p1;

assign kt_6_d0 = gmem1_addr_read_reg_782;

assign kt_7_address0 = zext_ln59_fu_695_p1;

assign kt_7_d0 = gmem1_addr_read_reg_782;

assign kt_8_address0 = zext_ln59_fu_695_p1;

assign kt_8_d0 = gmem1_addr_read_reg_782;

assign kt_9_address0 = zext_ln59_fu_695_p1;

assign kt_9_d0 = gmem1_addr_read_reg_782;

assign kt_address0 = zext_ln59_fu_695_p1;

assign kt_d0 = gmem1_addr_read_reg_782;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 8'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 1'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign m_axi_gmem2_ARADDR = 64'd0;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 32'd0;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_ARVALID = 1'b0;

assign m_axi_gmem2_AWADDR = 64'd0;

assign m_axi_gmem2_AWBURST = 2'd0;

assign m_axi_gmem2_AWCACHE = 4'd0;

assign m_axi_gmem2_AWID = 1'd0;

assign m_axi_gmem2_AWLEN = 32'd0;

assign m_axi_gmem2_AWLOCK = 2'd0;

assign m_axi_gmem2_AWPROT = 3'd0;

assign m_axi_gmem2_AWQOS = 4'd0;

assign m_axi_gmem2_AWREGION = 4'd0;

assign m_axi_gmem2_AWSIZE = 3'd0;

assign m_axi_gmem2_AWUSER = 1'd0;

assign m_axi_gmem2_AWVALID = 1'b0;

assign m_axi_gmem2_BREADY = 1'b0;

assign m_axi_gmem2_WDATA = 8'd0;

assign m_axi_gmem2_WID = 1'd0;

assign m_axi_gmem2_WLAST = 1'b0;

assign m_axi_gmem2_WSTRB = 1'd0;

assign m_axi_gmem2_WUSER = 1'd0;

assign m_axi_gmem2_WVALID = 1'b0;

assign select_ln58_1_fu_683_p3 = ((icmp_ln59_fu_663_p2[0:0] == 1'b1) ? add_ln58_1_fu_677_p2 : j_fu_164);

assign select_ln58_fu_669_p3 = ((icmp_ln59_fu_663_p2[0:0] == 1'b1) ? 7'd0 : d_fu_160);

assign trunc_ln58_fu_691_p1 = select_ln58_1_fu_683_p3[3:0];

assign vt_10_address0 = zext_ln59_fu_695_p1;

assign vt_10_d0 = gmem2_addr_read_reg_802;

assign vt_11_address0 = zext_ln59_fu_695_p1;

assign vt_11_d0 = gmem2_addr_read_reg_802;

assign vt_12_address0 = zext_ln59_fu_695_p1;

assign vt_12_d0 = gmem2_addr_read_reg_802;

assign vt_13_address0 = zext_ln59_fu_695_p1;

assign vt_13_d0 = gmem2_addr_read_reg_802;

assign vt_14_address0 = zext_ln59_fu_695_p1;

assign vt_14_d0 = gmem2_addr_read_reg_802;

assign vt_15_address0 = zext_ln59_fu_695_p1;

assign vt_15_d0 = gmem2_addr_read_reg_802;

assign vt_1_address0 = zext_ln59_fu_695_p1;

assign vt_1_d0 = gmem2_addr_read_reg_802;

assign vt_2_address0 = zext_ln59_fu_695_p1;

assign vt_2_d0 = gmem2_addr_read_reg_802;

assign vt_3_address0 = zext_ln59_fu_695_p1;

assign vt_3_d0 = gmem2_addr_read_reg_802;

assign vt_4_address0 = zext_ln59_fu_695_p1;

assign vt_4_d0 = gmem2_addr_read_reg_802;

assign vt_5_address0 = zext_ln59_fu_695_p1;

assign vt_5_d0 = gmem2_addr_read_reg_802;

assign vt_6_address0 = zext_ln59_fu_695_p1;

assign vt_6_d0 = gmem2_addr_read_reg_802;

assign vt_7_address0 = zext_ln59_fu_695_p1;

assign vt_7_d0 = gmem2_addr_read_reg_802;

assign vt_8_address0 = zext_ln59_fu_695_p1;

assign vt_8_d0 = gmem2_addr_read_reg_802;

assign vt_9_address0 = zext_ln59_fu_695_p1;

assign vt_9_d0 = gmem2_addr_read_reg_802;

assign vt_address0 = zext_ln59_fu_695_p1;

assign vt_d0 = gmem2_addr_read_reg_802;

assign zext_ln59_fu_695_p1 = select_ln58_fu_669_p3;

endmodule //streaming_attention_streaming_attention_Pipeline_LOAD_TILE_VITIS_LOOP_59_1
