// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module streaming_attention_streaming_attention_Pipeline_MAC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        q_reload,
        q_1_reload,
        q_2_reload,
        q_3_reload,
        q_4_reload,
        q_5_reload,
        q_6_reload,
        q_7_reload,
        q_8_reload,
        q_9_reload,
        q_10_reload,
        q_11_reload,
        q_12_reload,
        q_13_reload,
        q_14_reload,
        q_15_reload,
        q_16_reload,
        q_17_reload,
        q_18_reload,
        q_19_reload,
        q_20_reload,
        q_21_reload,
        q_22_reload,
        q_23_reload,
        q_24_reload,
        q_25_reload,
        q_26_reload,
        q_27_reload,
        q_28_reload,
        q_29_reload,
        q_30_reload,
        q_31_reload,
        q_32_reload,
        q_33_reload,
        q_34_reload,
        q_35_reload,
        q_36_reload,
        q_37_reload,
        q_38_reload,
        q_39_reload,
        q_40_reload,
        q_41_reload,
        q_42_reload,
        q_43_reload,
        q_44_reload,
        q_45_reload,
        q_46_reload,
        q_47_reload,
        q_48_reload,
        q_49_reload,
        q_50_reload,
        q_51_reload,
        q_52_reload,
        q_53_reload,
        q_54_reload,
        q_55_reload,
        q_56_reload,
        q_57_reload,
        q_58_reload,
        q_59_reload,
        q_60_reload,
        q_61_reload,
        q_62_reload,
        q_63_reload,
        kt_address0,
        kt_ce0,
        kt_q0,
        kt_1_address0,
        kt_1_ce0,
        kt_1_q0,
        kt_2_address0,
        kt_2_ce0,
        kt_2_q0,
        kt_3_address0,
        kt_3_ce0,
        kt_3_q0,
        kt_4_address0,
        kt_4_ce0,
        kt_4_q0,
        kt_5_address0,
        kt_5_ce0,
        kt_5_q0,
        kt_6_address0,
        kt_6_ce0,
        kt_6_q0,
        kt_7_address0,
        kt_7_ce0,
        kt_7_q0,
        kt_8_address0,
        kt_8_ce0,
        kt_8_q0,
        kt_9_address0,
        kt_9_ce0,
        kt_9_q0,
        kt_10_address0,
        kt_10_ce0,
        kt_10_q0,
        kt_11_address0,
        kt_11_ce0,
        kt_11_q0,
        kt_12_address0,
        kt_12_ce0,
        kt_12_q0,
        kt_13_address0,
        kt_13_ce0,
        kt_13_q0,
        kt_14_address0,
        kt_14_ce0,
        kt_14_q0,
        kt_15_address0,
        kt_15_ce0,
        kt_15_q0,
        add71_1539_out,
        add71_1539_out_ap_vld,
        add71_1438_out,
        add71_1438_out_ap_vld,
        add71_1337_out,
        add71_1337_out_ap_vld,
        add71_1236_out,
        add71_1236_out_ap_vld,
        add71_1135_out,
        add71_1135_out_ap_vld,
        add71_1034_out,
        add71_1034_out_ap_vld,
        add71_933_out,
        add71_933_out_ap_vld,
        add71_832_out,
        add71_832_out_ap_vld,
        add71_731_out,
        add71_731_out_ap_vld,
        add71_630_out,
        add71_630_out_ap_vld,
        add71_529_out,
        add71_529_out_ap_vld,
        add71_428_out,
        add71_428_out_ap_vld,
        add71_327_out,
        add71_327_out_ap_vld,
        add71_226_out,
        add71_226_out_ap_vld,
        add71_125_out,
        add71_125_out_ap_vld,
        add7124_out,
        add7124_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] q_reload;
input  [7:0] q_1_reload;
input  [7:0] q_2_reload;
input  [7:0] q_3_reload;
input  [7:0] q_4_reload;
input  [7:0] q_5_reload;
input  [7:0] q_6_reload;
input  [7:0] q_7_reload;
input  [7:0] q_8_reload;
input  [7:0] q_9_reload;
input  [7:0] q_10_reload;
input  [7:0] q_11_reload;
input  [7:0] q_12_reload;
input  [7:0] q_13_reload;
input  [7:0] q_14_reload;
input  [7:0] q_15_reload;
input  [7:0] q_16_reload;
input  [7:0] q_17_reload;
input  [7:0] q_18_reload;
input  [7:0] q_19_reload;
input  [7:0] q_20_reload;
input  [7:0] q_21_reload;
input  [7:0] q_22_reload;
input  [7:0] q_23_reload;
input  [7:0] q_24_reload;
input  [7:0] q_25_reload;
input  [7:0] q_26_reload;
input  [7:0] q_27_reload;
input  [7:0] q_28_reload;
input  [7:0] q_29_reload;
input  [7:0] q_30_reload;
input  [7:0] q_31_reload;
input  [7:0] q_32_reload;
input  [7:0] q_33_reload;
input  [7:0] q_34_reload;
input  [7:0] q_35_reload;
input  [7:0] q_36_reload;
input  [7:0] q_37_reload;
input  [7:0] q_38_reload;
input  [7:0] q_39_reload;
input  [7:0] q_40_reload;
input  [7:0] q_41_reload;
input  [7:0] q_42_reload;
input  [7:0] q_43_reload;
input  [7:0] q_44_reload;
input  [7:0] q_45_reload;
input  [7:0] q_46_reload;
input  [7:0] q_47_reload;
input  [7:0] q_48_reload;
input  [7:0] q_49_reload;
input  [7:0] q_50_reload;
input  [7:0] q_51_reload;
input  [7:0] q_52_reload;
input  [7:0] q_53_reload;
input  [7:0] q_54_reload;
input  [7:0] q_55_reload;
input  [7:0] q_56_reload;
input  [7:0] q_57_reload;
input  [7:0] q_58_reload;
input  [7:0] q_59_reload;
input  [7:0] q_60_reload;
input  [7:0] q_61_reload;
input  [7:0] q_62_reload;
input  [7:0] q_63_reload;
output  [5:0] kt_address0;
output   kt_ce0;
input  [7:0] kt_q0;
output  [5:0] kt_1_address0;
output   kt_1_ce0;
input  [7:0] kt_1_q0;
output  [5:0] kt_2_address0;
output   kt_2_ce0;
input  [7:0] kt_2_q0;
output  [5:0] kt_3_address0;
output   kt_3_ce0;
input  [7:0] kt_3_q0;
output  [5:0] kt_4_address0;
output   kt_4_ce0;
input  [7:0] kt_4_q0;
output  [5:0] kt_5_address0;
output   kt_5_ce0;
input  [7:0] kt_5_q0;
output  [5:0] kt_6_address0;
output   kt_6_ce0;
input  [7:0] kt_6_q0;
output  [5:0] kt_7_address0;
output   kt_7_ce0;
input  [7:0] kt_7_q0;
output  [5:0] kt_8_address0;
output   kt_8_ce0;
input  [7:0] kt_8_q0;
output  [5:0] kt_9_address0;
output   kt_9_ce0;
input  [7:0] kt_9_q0;
output  [5:0] kt_10_address0;
output   kt_10_ce0;
input  [7:0] kt_10_q0;
output  [5:0] kt_11_address0;
output   kt_11_ce0;
input  [7:0] kt_11_q0;
output  [5:0] kt_12_address0;
output   kt_12_ce0;
input  [7:0] kt_12_q0;
output  [5:0] kt_13_address0;
output   kt_13_ce0;
input  [7:0] kt_13_q0;
output  [5:0] kt_14_address0;
output   kt_14_ce0;
input  [7:0] kt_14_q0;
output  [5:0] kt_15_address0;
output   kt_15_ce0;
input  [7:0] kt_15_q0;
output  [21:0] add71_1539_out;
output   add71_1539_out_ap_vld;
output  [21:0] add71_1438_out;
output   add71_1438_out_ap_vld;
output  [21:0] add71_1337_out;
output   add71_1337_out_ap_vld;
output  [21:0] add71_1236_out;
output   add71_1236_out_ap_vld;
output  [21:0] add71_1135_out;
output   add71_1135_out_ap_vld;
output  [21:0] add71_1034_out;
output   add71_1034_out_ap_vld;
output  [21:0] add71_933_out;
output   add71_933_out_ap_vld;
output  [21:0] add71_832_out;
output   add71_832_out_ap_vld;
output  [21:0] add71_731_out;
output   add71_731_out_ap_vld;
output  [21:0] add71_630_out;
output   add71_630_out_ap_vld;
output  [21:0] add71_529_out;
output   add71_529_out_ap_vld;
output  [21:0] add71_428_out;
output   add71_428_out_ap_vld;
output  [21:0] add71_327_out;
output   add71_327_out_ap_vld;
output  [21:0] add71_226_out;
output   add71_226_out_ap_vld;
output  [21:0] add71_125_out;
output   add71_125_out_ap_vld;
output  [21:0] add7124_out;
output   add7124_out_ap_vld;

reg ap_idle;
reg kt_ce0;
reg kt_1_ce0;
reg kt_2_ce0;
reg kt_3_ce0;
reg kt_4_ce0;
reg kt_5_ce0;
reg kt_6_ce0;
reg kt_7_ce0;
reg kt_8_ce0;
reg kt_9_ce0;
reg kt_10_ce0;
reg kt_11_ce0;
reg kt_12_ce0;
reg kt_13_ce0;
reg kt_14_ce0;
reg kt_15_ce0;
reg add71_1539_out_ap_vld;
reg add71_1438_out_ap_vld;
reg add71_1337_out_ap_vld;
reg add71_1236_out_ap_vld;
reg add71_1135_out_ap_vld;
reg add71_1034_out_ap_vld;
reg add71_933_out_ap_vld;
reg add71_832_out_ap_vld;
reg add71_731_out_ap_vld;
reg add71_630_out_ap_vld;
reg add71_529_out_ap_vld;
reg add71_428_out_ap_vld;
reg add71_327_out_ap_vld;
reg add71_226_out_ap_vld;
reg add71_125_out_ap_vld;
reg add7124_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln75_fu_1084_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln75_reg_1777;
reg   [0:0] icmp_ln75_reg_1777_pp0_iter1_reg;
reg   [0:0] icmp_ln75_reg_1777_pp0_iter2_reg;
wire   [7:0] tmp_1_fu_1116_p66;
reg   [7:0] tmp_1_reg_1781;
wire  signed [15:0] sext_ln79_fu_1255_p1;
wire   [63:0] zext_ln75_fu_1096_p1;
wire    ap_block_pp0_stage0;
reg   [21:0] dot_16_fu_224;
wire  signed [21:0] grp_fu_1498_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_16_load_1;
wire    ap_loop_init;
reg   [21:0] dot_17_fu_228;
wire  signed [21:0] grp_fu_1507_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_17_load_1;
reg   [21:0] dot_18_fu_232;
wire  signed [21:0] grp_fu_1516_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_18_load_1;
reg   [21:0] dot_19_fu_236;
wire  signed [21:0] grp_fu_1525_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_19_load_1;
reg   [21:0] dot_20_fu_240;
wire  signed [21:0] grp_fu_1534_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_20_load_1;
reg   [21:0] dot_21_fu_244;
wire  signed [21:0] grp_fu_1543_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_21_load_1;
reg   [21:0] dot_22_fu_248;
wire  signed [21:0] grp_fu_1552_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_22_load_1;
reg   [21:0] dot_23_fu_252;
wire  signed [21:0] grp_fu_1561_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_23_load_1;
reg   [21:0] dot_24_fu_256;
wire  signed [21:0] grp_fu_1570_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_24_load_1;
reg   [21:0] dot_25_fu_260;
wire  signed [21:0] grp_fu_1579_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_25_load_1;
reg   [21:0] dot_26_fu_264;
wire  signed [21:0] grp_fu_1588_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_26_load_1;
reg   [21:0] dot_27_fu_268;
wire  signed [21:0] grp_fu_1597_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_27_load_1;
reg   [21:0] dot_28_fu_272;
wire  signed [21:0] grp_fu_1606_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_28_load_1;
reg   [21:0] dot_29_fu_276;
wire  signed [21:0] grp_fu_1615_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_29_load_1;
reg   [21:0] dot_30_fu_280;
wire  signed [21:0] grp_fu_1624_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_30_load_1;
reg   [21:0] dot_31_fu_284;
wire  signed [21:0] grp_fu_1633_p3;
reg  signed [21:0] ap_sig_allocacmp_dot_31_load_1;
reg   [6:0] d_fu_288;
wire   [6:0] add_ln75_fu_1090_p2;
reg   [6:0] ap_sig_allocacmp_d_2;
wire    ap_block_pp0_stage0_01001;
wire  signed [7:0] grp_fu_1498_p1;
wire  signed [7:0] grp_fu_1507_p1;
wire  signed [7:0] grp_fu_1516_p1;
wire  signed [7:0] grp_fu_1525_p1;
wire  signed [7:0] grp_fu_1534_p1;
wire  signed [7:0] grp_fu_1543_p1;
wire  signed [7:0] grp_fu_1552_p1;
wire  signed [7:0] grp_fu_1561_p1;
wire  signed [7:0] grp_fu_1570_p1;
wire  signed [7:0] grp_fu_1579_p1;
wire  signed [7:0] grp_fu_1588_p1;
wire  signed [7:0] grp_fu_1597_p1;
wire  signed [7:0] grp_fu_1606_p1;
wire  signed [7:0] grp_fu_1615_p1;
wire  signed [7:0] grp_fu_1624_p1;
wire  signed [7:0] grp_fu_1633_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

streaming_attention_mux_647_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 7 ),
    .dout_WIDTH( 8 ))
mux_647_8_1_1_U167(
    .din0(q_reload),
    .din1(q_1_reload),
    .din2(q_2_reload),
    .din3(q_3_reload),
    .din4(q_4_reload),
    .din5(q_5_reload),
    .din6(q_6_reload),
    .din7(q_7_reload),
    .din8(q_8_reload),
    .din9(q_9_reload),
    .din10(q_10_reload),
    .din11(q_11_reload),
    .din12(q_12_reload),
    .din13(q_13_reload),
    .din14(q_14_reload),
    .din15(q_15_reload),
    .din16(q_16_reload),
    .din17(q_17_reload),
    .din18(q_18_reload),
    .din19(q_19_reload),
    .din20(q_20_reload),
    .din21(q_21_reload),
    .din22(q_22_reload),
    .din23(q_23_reload),
    .din24(q_24_reload),
    .din25(q_25_reload),
    .din26(q_26_reload),
    .din27(q_27_reload),
    .din28(q_28_reload),
    .din29(q_29_reload),
    .din30(q_30_reload),
    .din31(q_31_reload),
    .din32(q_32_reload),
    .din33(q_33_reload),
    .din34(q_34_reload),
    .din35(q_35_reload),
    .din36(q_36_reload),
    .din37(q_37_reload),
    .din38(q_38_reload),
    .din39(q_39_reload),
    .din40(q_40_reload),
    .din41(q_41_reload),
    .din42(q_42_reload),
    .din43(q_43_reload),
    .din44(q_44_reload),
    .din45(q_45_reload),
    .din46(q_46_reload),
    .din47(q_47_reload),
    .din48(q_48_reload),
    .din49(q_49_reload),
    .din50(q_50_reload),
    .din51(q_51_reload),
    .din52(q_52_reload),
    .din53(q_53_reload),
    .din54(q_54_reload),
    .din55(q_55_reload),
    .din56(q_56_reload),
    .din57(q_57_reload),
    .din58(q_58_reload),
    .din59(q_59_reload),
    .din60(q_60_reload),
    .din61(q_61_reload),
    .din62(q_62_reload),
    .din63(q_63_reload),
    .din64(ap_sig_allocacmp_d_2),
    .dout(tmp_1_fu_1116_p66)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U168(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_q0),
    .din1(grp_fu_1498_p1),
    .din2(ap_sig_allocacmp_dot_16_load_1),
    .ce(1'b1),
    .dout(grp_fu_1498_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U169(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_1_q0),
    .din1(grp_fu_1507_p1),
    .din2(ap_sig_allocacmp_dot_17_load_1),
    .ce(1'b1),
    .dout(grp_fu_1507_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U170(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_2_q0),
    .din1(grp_fu_1516_p1),
    .din2(ap_sig_allocacmp_dot_18_load_1),
    .ce(1'b1),
    .dout(grp_fu_1516_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U171(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_3_q0),
    .din1(grp_fu_1525_p1),
    .din2(ap_sig_allocacmp_dot_19_load_1),
    .ce(1'b1),
    .dout(grp_fu_1525_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U172(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_4_q0),
    .din1(grp_fu_1534_p1),
    .din2(ap_sig_allocacmp_dot_20_load_1),
    .ce(1'b1),
    .dout(grp_fu_1534_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U173(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_5_q0),
    .din1(grp_fu_1543_p1),
    .din2(ap_sig_allocacmp_dot_21_load_1),
    .ce(1'b1),
    .dout(grp_fu_1543_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U174(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_6_q0),
    .din1(grp_fu_1552_p1),
    .din2(ap_sig_allocacmp_dot_22_load_1),
    .ce(1'b1),
    .dout(grp_fu_1552_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_7_q0),
    .din1(grp_fu_1561_p1),
    .din2(ap_sig_allocacmp_dot_23_load_1),
    .ce(1'b1),
    .dout(grp_fu_1561_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U176(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_8_q0),
    .din1(grp_fu_1570_p1),
    .din2(ap_sig_allocacmp_dot_24_load_1),
    .ce(1'b1),
    .dout(grp_fu_1570_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U177(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_9_q0),
    .din1(grp_fu_1579_p1),
    .din2(ap_sig_allocacmp_dot_25_load_1),
    .ce(1'b1),
    .dout(grp_fu_1579_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U178(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_10_q0),
    .din1(grp_fu_1588_p1),
    .din2(ap_sig_allocacmp_dot_26_load_1),
    .ce(1'b1),
    .dout(grp_fu_1588_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U179(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_11_q0),
    .din1(grp_fu_1597_p1),
    .din2(ap_sig_allocacmp_dot_27_load_1),
    .ce(1'b1),
    .dout(grp_fu_1597_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U180(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_12_q0),
    .din1(grp_fu_1606_p1),
    .din2(ap_sig_allocacmp_dot_28_load_1),
    .ce(1'b1),
    .dout(grp_fu_1606_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U181(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_13_q0),
    .din1(grp_fu_1615_p1),
    .din2(ap_sig_allocacmp_dot_29_load_1),
    .ce(1'b1),
    .dout(grp_fu_1615_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U182(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_14_q0),
    .din1(grp_fu_1624_p1),
    .din2(ap_sig_allocacmp_dot_30_load_1),
    .ce(1'b1),
    .dout(grp_fu_1624_p3)
);

streaming_attention_mac_muladd_8s_8s_22s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
mac_muladd_8s_8s_22s_22_4_1_U183(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kt_15_q0),
    .din1(grp_fu_1633_p1),
    .din2(ap_sig_allocacmp_dot_31_load_1),
    .ce(1'b1),
    .dout(grp_fu_1633_p3)
);

streaming_attention_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln75_fu_1084_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            d_fu_288 <= add_ln75_fu_1090_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            d_fu_288 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_16_fu_224 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_16_fu_224 <= grp_fu_1498_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_17_fu_228 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_17_fu_228 <= grp_fu_1507_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_18_fu_232 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_18_fu_232 <= grp_fu_1516_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_19_fu_236 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_19_fu_236 <= grp_fu_1525_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_20_fu_240 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_20_fu_240 <= grp_fu_1534_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_21_fu_244 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_21_fu_244 <= grp_fu_1543_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_22_fu_248 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_22_fu_248 <= grp_fu_1552_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_23_fu_252 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_23_fu_252 <= grp_fu_1561_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_24_fu_256 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_24_fu_256 <= grp_fu_1570_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_25_fu_260 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_25_fu_260 <= grp_fu_1579_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_26_fu_264 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_26_fu_264 <= grp_fu_1588_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_27_fu_268 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_27_fu_268 <= grp_fu_1597_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_28_fu_272 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_28_fu_272 <= grp_fu_1606_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_29_fu_276 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_29_fu_276 <= grp_fu_1615_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_30_fu_280 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_30_fu_280 <= grp_fu_1624_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dot_31_fu_284 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            dot_31_fu_284 <= grp_fu_1633_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln75_reg_1777 <= icmp_ln75_fu_1084_p2;
        icmp_ln75_reg_1777_pp0_iter1_reg <= icmp_ln75_reg_1777;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln75_reg_1777_pp0_iter2_reg <= icmp_ln75_reg_1777_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln75_fu_1084_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_reg_1781 <= tmp_1_fu_1116_p66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add7124_out_ap_vld = 1'b1;
    end else begin
        add7124_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1034_out_ap_vld = 1'b1;
    end else begin
        add71_1034_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1135_out_ap_vld = 1'b1;
    end else begin
        add71_1135_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1236_out_ap_vld = 1'b1;
    end else begin
        add71_1236_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_125_out_ap_vld = 1'b1;
    end else begin
        add71_125_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1337_out_ap_vld = 1'b1;
    end else begin
        add71_1337_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1438_out_ap_vld = 1'b1;
    end else begin
        add71_1438_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_1539_out_ap_vld = 1'b1;
    end else begin
        add71_1539_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_226_out_ap_vld = 1'b1;
    end else begin
        add71_226_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_327_out_ap_vld = 1'b1;
    end else begin
        add71_327_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_428_out_ap_vld = 1'b1;
    end else begin
        add71_428_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_529_out_ap_vld = 1'b1;
    end else begin
        add71_529_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_630_out_ap_vld = 1'b1;
    end else begin
        add71_630_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_731_out_ap_vld = 1'b1;
    end else begin
        add71_731_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_832_out_ap_vld = 1'b1;
    end else begin
        add71_832_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln75_reg_1777_pp0_iter2_reg == 1'd1))) begin
        add71_933_out_ap_vld = 1'b1;
    end else begin
        add71_933_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln75_fu_1084_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_d_2 = 7'd0;
    end else begin
        ap_sig_allocacmp_d_2 = d_fu_288;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_16_load_1 = grp_fu_1498_p3;
    end else begin
        ap_sig_allocacmp_dot_16_load_1 = dot_16_fu_224;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_17_load_1 = grp_fu_1507_p3;
    end else begin
        ap_sig_allocacmp_dot_17_load_1 = dot_17_fu_228;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_18_load_1 = grp_fu_1516_p3;
    end else begin
        ap_sig_allocacmp_dot_18_load_1 = dot_18_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_19_load_1 = grp_fu_1525_p3;
    end else begin
        ap_sig_allocacmp_dot_19_load_1 = dot_19_fu_236;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_20_load_1 = grp_fu_1534_p3;
    end else begin
        ap_sig_allocacmp_dot_20_load_1 = dot_20_fu_240;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_21_load_1 = grp_fu_1543_p3;
    end else begin
        ap_sig_allocacmp_dot_21_load_1 = dot_21_fu_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_22_load_1 = grp_fu_1552_p3;
    end else begin
        ap_sig_allocacmp_dot_22_load_1 = dot_22_fu_248;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_23_load_1 = grp_fu_1561_p3;
    end else begin
        ap_sig_allocacmp_dot_23_load_1 = dot_23_fu_252;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_24_load_1 = grp_fu_1570_p3;
    end else begin
        ap_sig_allocacmp_dot_24_load_1 = dot_24_fu_256;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_25_load_1 = grp_fu_1579_p3;
    end else begin
        ap_sig_allocacmp_dot_25_load_1 = dot_25_fu_260;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_26_load_1 = grp_fu_1588_p3;
    end else begin
        ap_sig_allocacmp_dot_26_load_1 = dot_26_fu_264;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_27_load_1 = grp_fu_1597_p3;
    end else begin
        ap_sig_allocacmp_dot_27_load_1 = dot_27_fu_268;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_28_load_1 = grp_fu_1606_p3;
    end else begin
        ap_sig_allocacmp_dot_28_load_1 = dot_28_fu_272;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_29_load_1 = grp_fu_1615_p3;
    end else begin
        ap_sig_allocacmp_dot_29_load_1 = dot_29_fu_276;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_30_load_1 = grp_fu_1624_p3;
    end else begin
        ap_sig_allocacmp_dot_30_load_1 = dot_30_fu_280;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_dot_31_load_1 = grp_fu_1633_p3;
    end else begin
        ap_sig_allocacmp_dot_31_load_1 = dot_31_fu_284;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_10_ce0 = 1'b1;
    end else begin
        kt_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_11_ce0 = 1'b1;
    end else begin
        kt_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_12_ce0 = 1'b1;
    end else begin
        kt_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_13_ce0 = 1'b1;
    end else begin
        kt_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_14_ce0 = 1'b1;
    end else begin
        kt_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_15_ce0 = 1'b1;
    end else begin
        kt_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_1_ce0 = 1'b1;
    end else begin
        kt_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_2_ce0 = 1'b1;
    end else begin
        kt_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_3_ce0 = 1'b1;
    end else begin
        kt_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_4_ce0 = 1'b1;
    end else begin
        kt_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_5_ce0 = 1'b1;
    end else begin
        kt_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_6_ce0 = 1'b1;
    end else begin
        kt_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_7_ce0 = 1'b1;
    end else begin
        kt_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_8_ce0 = 1'b1;
    end else begin
        kt_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_9_ce0 = 1'b1;
    end else begin
        kt_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kt_ce0 = 1'b1;
    end else begin
        kt_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add7124_out = dot_16_fu_224;

assign add71_1034_out = dot_26_fu_264;

assign add71_1135_out = dot_27_fu_268;

assign add71_1236_out = dot_28_fu_272;

assign add71_125_out = dot_17_fu_228;

assign add71_1337_out = dot_29_fu_276;

assign add71_1438_out = dot_30_fu_280;

assign add71_1539_out = dot_31_fu_284;

assign add71_226_out = dot_18_fu_232;

assign add71_327_out = dot_19_fu_236;

assign add71_428_out = dot_20_fu_240;

assign add71_529_out = dot_21_fu_244;

assign add71_630_out = dot_22_fu_248;

assign add71_731_out = dot_23_fu_252;

assign add71_832_out = dot_24_fu_256;

assign add71_933_out = dot_25_fu_260;

assign add_ln75_fu_1090_p2 = (ap_sig_allocacmp_d_2 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1498_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1507_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1516_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1525_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1534_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1543_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1552_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1561_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1570_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1579_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1588_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1597_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1606_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1615_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1624_p1 = sext_ln79_fu_1255_p1;

assign grp_fu_1633_p1 = sext_ln79_fu_1255_p1;

assign icmp_ln75_fu_1084_p2 = ((ap_sig_allocacmp_d_2 == 7'd64) ? 1'b1 : 1'b0);

assign kt_10_address0 = zext_ln75_fu_1096_p1;

assign kt_11_address0 = zext_ln75_fu_1096_p1;

assign kt_12_address0 = zext_ln75_fu_1096_p1;

assign kt_13_address0 = zext_ln75_fu_1096_p1;

assign kt_14_address0 = zext_ln75_fu_1096_p1;

assign kt_15_address0 = zext_ln75_fu_1096_p1;

assign kt_1_address0 = zext_ln75_fu_1096_p1;

assign kt_2_address0 = zext_ln75_fu_1096_p1;

assign kt_3_address0 = zext_ln75_fu_1096_p1;

assign kt_4_address0 = zext_ln75_fu_1096_p1;

assign kt_5_address0 = zext_ln75_fu_1096_p1;

assign kt_6_address0 = zext_ln75_fu_1096_p1;

assign kt_7_address0 = zext_ln75_fu_1096_p1;

assign kt_8_address0 = zext_ln75_fu_1096_p1;

assign kt_9_address0 = zext_ln75_fu_1096_p1;

assign kt_address0 = zext_ln75_fu_1096_p1;

assign sext_ln79_fu_1255_p1 = $signed(tmp_1_reg_1781);

assign zext_ln75_fu_1096_p1 = ap_sig_allocacmp_d_2;

endmodule //streaming_attention_streaming_attention_Pipeline_MAC
